
#Generated by fsm_gen.py
#from fsm_lex.txt
#!!! DO NOT EDIT MANUALLY !!!

class fsm_lex:
  INVALID_STATE = -1
  ERROR_ANSWER = -1
  OK_ANSWER = 0
  ignore_error = False

  #Events
  ALPHA=0
  APOS=1
  ASTERISK=2
  BLANK=3
  DIGIT=4
  LBRACKET=5
  NEWLINE=6
  NUMBER=7
  QUOT=8
  RBRACKET=9
  SLASH=10
  SYMBOL=11
  EVENT_COUNT=12
  events = {
    ALPHA : 'ALPHA',
    APOS : 'APOS',
    ASTERISK : 'ASTERISK',
    BLANK : 'BLANK',
    DIGIT : 'DIGIT',
    LBRACKET : 'LBRACKET',
    NEWLINE : 'NEWLINE',
    NUMBER : 'NUMBER',
    QUOT : 'QUOT',
    RBRACKET : 'RBRACKET',
    SLASH : 'SLASH',
    SYMBOL : 'SYMBOL',
    }
  #States
  AESCAPE=0
  ASTRING=1
  IDENT=2
  IDLE=3
  MASK=4
  QESCAPE=5
  QSTRING=6
  SECTION=7
  STATEMENT=8
  WAIT_NEWLINE=9
  STATE_COUNT=10
  states = {
    AESCAPE : 'AESCAPE',
    ASTRING : 'ASTRING',
    IDENT : 'IDENT',
    IDLE : 'IDLE',
    MASK : 'MASK',
    QESCAPE : 'QESCAPE',
    QSTRING : 'QSTRING',
    SECTION : 'SECTION',
    STATEMENT : 'STATEMENT',
    WAIT_NEWLINE : 'WAIT_NEWLINE',
    }
  #callbacks

  def on_begin_ident(self, evt):
    print("on_begin_ident({0}({1})) Next state={2}({3})".format(self.events.get(evt, '????'), evt, self.states.get(self.current_state), self.current_state))
    return self.OK_ANSWER #Pure virtual


  def on_begin_section(self, evt):
    print("on_begin_section({0}({1})) Next state={2}({3})".format(self.events.get(evt, '????'), evt, self.states.get(self.current_state), self.current_state))
    return self.OK_ANSWER #Pure virtual


  def on_begin_statement(self, evt):
    print("on_begin_statement({0}({1})) Next state={2}({3})".format(self.events.get(evt, '????'), evt, self.states.get(self.current_state), self.current_state))
    return self.OK_ANSWER #Pure virtual


  def on_begin_string(self, evt):
    print("on_begin_string({0}({1})) Next state={2}({3})".format(self.events.get(evt, '????'), evt, self.states.get(self.current_state), self.current_state))
    return self.OK_ANSWER #Pure virtual


  def on_end_ident(self, evt):
    print("on_end_ident({0}({1})) Next state={2}({3})".format(self.events.get(evt, '????'), evt, self.states.get(self.current_state), self.current_state))
    return self.OK_ANSWER #Pure virtual


  def on_end_section(self, evt):
    print("on_end_section({0}({1})) Next state={2}({3})".format(self.events.get(evt, '????'), evt, self.states.get(self.current_state), self.current_state))
    return self.OK_ANSWER #Pure virtual


  def on_end_statement(self, evt):
    print("on_end_statement({0}({1})) Next state={2}({3})".format(self.events.get(evt, '????'), evt, self.states.get(self.current_state), self.current_state))
    return self.OK_ANSWER #Pure virtual


  def on_end_string(self, evt):
    print("on_end_string({0}({1})) Next state={2}({3})".format(self.events.get(evt, '????'), evt, self.states.get(self.current_state), self.current_state))
    return self.OK_ANSWER #Pure virtual


  def __init__(self):

    #AESCAPE events
    aescape_events = (
       ( self.ASTRING, None ) #ALPHA
      ,( self.ASTRING, None ) #APOS
      ,( self.ASTRING, None ) #ASTERISK
      ,( self.ASTRING, None ) #BLANK
      ,( self.ASTRING, None ) #DIGIT
      ,( self.ASTRING, None ) #LBRACKET
      ,( self.ASTRING, None ) #NEWLINE
      ,( self.ASTRING, None ) #NUMBER
      ,( self.ASTRING, None ) #QUOT
      ,( self.ASTRING, None ) #RBRACKET
      ,( self.ASTRING, None ) #SLASH
      ,( self.ASTRING, None ) #SYMBOL
    )


    #ASTRING events
    astring_events = (
       ( self.ASTRING, None ) #ALPHA
      ,( self.STATEMENT, self.on_end_string ) #APOS
      ,( self.ASTRING, None ) #ASTERISK
      ,( self.ASTRING, None ) #BLANK
      ,( self.ASTRING, None ) #DIGIT
      ,( self.ASTRING, None ) #LBRACKET
      ,( self.ASTRING, None ) #NEWLINE
      ,( self.ASTRING, None ) #NUMBER
      ,( self.ASTRING, None ) #QUOT
      ,( self.ASTRING, None ) #RBRACKET
      ,( self.AESCAPE, None ) #SLASH
      ,( self.ASTRING, None ) #SYMBOL
    )


    #IDENT events
    ident_events = (
       ( self.IDENT, None ) #ALPHA
      ,( self.INVALID_STATE, None ) #APOS
      ,( self.INVALID_STATE, None ) #ASTERISK
      ,( self.STATEMENT, self.on_end_ident ) #BLANK
      ,( self.IDENT, None ) #DIGIT
      ,( self.INVALID_STATE, None ) #LBRACKET
      ,( self.IDLE, self.on_end_statement ) #NEWLINE
      ,( self.WAIT_NEWLINE, self.on_end_statement ) #NUMBER
    )


    #IDLE events
    idle_events = (
       ( self.IDENT, self.on_begin_statement ) #ALPHA
      ,( self.INVALID_STATE, None ) #APOS
      ,( self.MASK, self.on_begin_statement ) #ASTERISK
      ,( self.IDLE, None ) #BLANK
      ,( self.INVALID_STATE, None ) #DIGIT
      ,( self.SECTION, self.on_begin_section ) #LBRACKET
      ,( self.IDLE, None ) #NEWLINE
      ,( self.WAIT_NEWLINE, None ) #NUMBER
    )


    #MASK events
    mask_events = (
       ( self.STATEMENT, self.on_end_ident ) #BLANK
      ,( self.INVALID_STATE, None ) #DIGIT
      ,( self.INVALID_STATE, None ) #LBRACKET
      ,( self.IDLE, self.on_end_statement ) #NEWLINE
      ,( self.WAIT_NEWLINE, self.on_end_statement ) #NUMBER
    )


    #QESCAPE events
    qescape_events = (
       ( self.QSTRING, None ) #ALPHA
      ,( self.QSTRING, None ) #APOS
      ,( self.QSTRING, None ) #ASTERISK
      ,( self.QSTRING, None ) #BLANK
      ,( self.QSTRING, None ) #DIGIT
      ,( self.QSTRING, None ) #LBRACKET
      ,( self.QSTRING, None ) #NEWLINE
      ,( self.QSTRING, None ) #NUMBER
      ,( self.QSTRING, None ) #QUOT
      ,( self.QSTRING, None ) #RBRACKET
      ,( self.QSTRING, None ) #SLASH
      ,( self.QSTRING, None ) #SYMBOL
    )


    #QSTRING events
    qstring_events = (
       ( self.QSTRING, None ) #ALPHA
      ,( self.QSTRING, None ) #APOS
      ,( self.QSTRING, None ) #ASTERISK
      ,( self.QSTRING, None ) #BLANK
      ,( self.QSTRING, None ) #DIGIT
      ,( self.QSTRING, None ) #LBRACKET
      ,( self.QSTRING, None ) #NEWLINE
      ,( self.QSTRING, None ) #NUMBER
      ,( self.STATEMENT, self.on_end_string ) #QUOT
      ,( self.QSTRING, None ) #RBRACKET
      ,( self.QESCAPE, None ) #SLASH
      ,( self.QSTRING, None ) #SYMBOL
    )


    #SECTION events
    section_events = (
       ( self.SECTION, None ) #ALPHA
      ,( self.INVALID_STATE, None ) #APOS
      ,( self.INVALID_STATE, None ) #ASTERISK
      ,( self.INVALID_STATE, None ) #BLANK
      ,( self.SECTION, None ) #DIGIT
      ,( self.INVALID_STATE, None ) #LBRACKET
      ,( self.INVALID_STATE, None ) #NEWLINE
      ,( self.INVALID_STATE, None ) #NUMBER
      ,( self.INVALID_STATE, None ) #QUOT
      ,( self.WAIT_NEWLINE, self.on_end_section ) #RBRACKET
      ,( self.INVALID_STATE, None ) #SLASH
      ,( self.SECTION, None ) #SYMBOL
    )


    #STATEMENT events
    statement_events = (
       ( self.IDENT, self.on_begin_ident ) #ALPHA
      ,( self.ASTRING, self.on_begin_string ) #APOS
      ,( self.MASK, self.on_begin_ident ) #ASTERISK
      ,( self.STATEMENT, None ) #BLANK
      ,( self.INVALID_STATE, None ) #DIGIT
      ,( self.INVALID_STATE, None ) #LBRACKET
      ,( self.IDLE, self.on_end_statement ) #NEWLINE
      ,( self.WAIT_NEWLINE, self.on_end_statement ) #NUMBER
      ,( self.QSTRING, self.on_begin_string ) #QUOT
    )


    #WAIT_NEWLINE events
    wait_newline_events = (
       ( self.WAIT_NEWLINE, None ) #ALPHA
      ,( self.WAIT_NEWLINE, None ) #APOS
      ,( self.WAIT_NEWLINE, None ) #ASTERISK
      ,( self.WAIT_NEWLINE, None ) #BLANK
      ,( self.WAIT_NEWLINE, None ) #DIGIT
      ,( self.WAIT_NEWLINE, None ) #LBRACKET
      ,( self.IDLE, None ) #NEWLINE
      ,( self.WAIT_NEWLINE, None ) #NUMBER
      ,( self.WAIT_NEWLINE, None ) #QUOT
      ,( self.WAIT_NEWLINE, None ) #RBRACKET
      ,( self.WAIT_NEWLINE, None ) #SLASH
      ,( self.WAIT_NEWLINE, None ) #SYMBOL
    )


    #State table
    self.state_table = (
      #AESCAPE state
       ( self.ALPHA,  aescape_events )
      #ASTRING state
      ,( self.ALPHA,  astring_events )
      #IDENT state
      ,( self.ALPHA,  ident_events )
      #IDLE state
      ,( self.ALPHA,  idle_events )
      #MASK state
      ,( self.BLANK,  mask_events )
      #QESCAPE state
      ,( self.ALPHA,  qescape_events )
      #QSTRING state
      ,( self.ALPHA,  qstring_events )
      #SECTION state
      ,( self.ALPHA,  section_events )
      #STATEMENT state
      ,( self.ALPHA,  statement_events )
      #WAIT_NEWLINE state
      ,( self.ALPHA,  wait_newline_events )
    )
    self.current_state = self.IDLE

  def error(self, evt):
    print("Invalid event={0}({1}) for state={2}({3})".format(self.events.get(evt, '????'), evt, self.states.get(self.current_state), self.current_state))

  def handle(self, evt):
    if self.current_state < 0 or self.current_state >= self.STATE_COUNT:
      if not self.ignore_error:
        self.error(evt)
        self.current_state = self.IDLE;
      return self.ERROR_ANSWER;

    state_entry = self.state_table[self.current_state]
    index = evt - state_entry[0]
    if(index < 0
      or index >= len(state_entry[1])
      or self.INVALID_STATE == state_entry[1][index][0]):
      if not self.ignore_error:
        self.error(evt)
        self.current_state = self.IDLE;
      return self.ERROR_ANSWER;

    self.current_state = state_entry[1][index][0];
    if state_entry[1][index][1]:
      return state_entry[1][index][1](evt);
    return self.OK_ANSWER;
# ********* class fsm_lex
if __name__ == "__main__":
  obj = fsm_lex()

  obj.handle(obj.ALPHA)
  obj.handle(obj.APOS)
  obj.handle(obj.ASTERISK)
  obj.handle(obj.BLANK)
  obj.handle(obj.DIGIT)
  obj.handle(obj.LBRACKET)
  obj.handle(obj.NEWLINE)
  obj.handle(obj.NUMBER)
  obj.handle(obj.QUOT)
  obj.handle(obj.RBRACKET)
  obj.handle(obj.SLASH)
  obj.handle(obj.SYMBOL)
